openapi: 3.0.0
info:
  title: Course Companion FTE - Web App API Integration
  version: 1.0.0
  description: Frontend API client specification for web app backend integration

servers:
  - url: ${NEXT_PUBLIC_BACKEND_URL}/api/v1
    description: Backend API base URL (from environment variables)

paths:
  # Auth endpoints
  /auth/login:
    post:
      summary: User login
      operationId: login
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
      responses:
        '200':
          description: Login successful with JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  token:
                    type: string
        '401':
          description: Invalid credentials

  /auth/register:
    post:
      summary: User registration
      operationId: register
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input or user already exists

  # Content endpoints
  /chapters:
    get:
      summary: List all chapters
      operationId: listChapters
      tags: [Content]
      responses:
        '200':
          description: List of chapters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chapter'

  /chapters/{chapter_id}:
    get:
      summary: Get chapter content
      operationId: getChapter
      tags: [Content]
      parameters:
        - name: chapter_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Chapter content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChapterDetail'
        '404':
          description: Chapter not found

  # Quiz endpoints
  /quizzes:
    get:
      summary: List all quizzes
      operationId: listQuizzes
      tags: [Quiz]
      responses:
        '200':
          description: List of quizzes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quiz'

  /quizzes/{quiz_id}:
    get:
      summary: Get quiz details
      operationId: getQuiz
      tags: [Quiz]
      parameters:
        - name: quiz_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Quiz with questions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizDetail'

  /quizzes/{quiz_id}/submit:
    post:
      summary: Submit quiz answers
      operationId: submitQuiz
      tags: [Quiz]
      parameters:
        - name: quiz_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [answers]
              properties:
                answers:
                  type: object
                  additionalProperties:
                    type: string
                  example:
                    q1: "A"
                    q2: "C"
                    q3: "B"
      responses:
        '200':
          description: Quiz results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizResult'

  # Progress endpoints
  /progress/{user_id}:
    get:
      summary: Get user progress
      operationId: getProgress
      tags: [Progress]
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Progress data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Progress'

    put:
      summary: Update user progress
      operationId: updateProgress
      tags: [Progress]
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [chapter_id]
              properties:
                chapter_id:
                  type: string
                  format: uuid
      responses:
        '200':
          description: Progress updated successfully

  # Streak endpoints
  /streaks/{user_id}:
    get:
      summary: Get user streak
      operationId: getStreak
      tags: [Progress]
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Streak data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Streak'

  /streaks/{user_id}/checkin:
    post:
      summary: Record daily activity
      operationId: recordCheckin
      tags: [Progress]
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Streak updated successfully

  # Access control
  /access/check:
    post:
      summary: Check user access rights
      operationId: checkAccess
      tags: [Access]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user_id, resource]
              properties:
                user_id:
                  type: string
                  format: uuid
                resource:
                  type: string
                  example: "chapter-4"
      responses:
        '200':
          description: Access check result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessResponse'
        '403':
          description: Access denied

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        tier:
          type: string
          enum: [free, premium, pro]
        created_at:
          type: string
          format: date-time

    Chapter:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        order:
          type: integer
        difficulty_level:
          type: string
          enum: [beginner, intermediate, advanced]
        estimated_time:
          type: integer
          description: Estimated reading time in minutes

    ChapterDetail:
      allOf:
        - $ref: '#/components/schemas/Chapter'
        - type: object
          properties:
            content:
              type: string
              description: Full markdown content
            quiz_id:
              type: string
              format: uuid
            next_chapter_id:
              type: string
              format: uuid
              nullable: true
            previous_chapter_id:
              type: string
              format: uuid
              nullable: true

    QuizDetail:
      type: object
      properties:
        id:
          type: string
          format: uuid
        chapter_id:
          type: string
          format: uuid
        title:
          type: string
        difficulty:
          type: string
          enum: [beginner, intermediate, advanced]
        questions:
          type: array
          items:
            $ref: '#/components/schemas/Question'

    Question:
      type: object
      properties:
        id:
          type: string
          format: uuid
        question_text:
          type: string
        options:
          type: object
          additionalProperties:
            type: string
          example:
            A: "Option A"
            B: "Option B"
            C: "Option C"
            D: "Option D"
        order:
          type: integer

    QuizResult:
      type: object
      properties:
        id:
          type: string
          format: uuid
        score:
          type: integer
          description: Score percentage (0-100)
        passed:
          type: boolean
        feedback:
          type: string
        answers:
          type: object
          additionalProperties:
            type: string
        completed_at:
          type: string
          format: date-time

    Progress:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        completed_chapters:
          type: array
          items:
            type: string
            format: uuid
        current_chapter_id:
          type: string
          format: uuid
          nullable: true
        last_activity:
          type: string
          format: date-time
        completion_percentage:
          type: number
          description: Calculated percentage (0-100)

    Streak:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        current_streak:
          type: integer
        longest_streak:
          type: integer
        last_checkin:
          type: string
          format: date
          nullable: true

    AccessResponse:
      type: object
      properties:
        has_access:
          type: boolean
        tier:
          type: string
          enum: [free, premium, pro]
        reason:
          type: string
          nullable: true
