"""Add llm_costs table for Phase 2

Revision ID: 002_add_llm_costs_table
Revises:
Create Date: 2026-02-01

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002_add_llm_costs_table'
down_revision: Union[str, Sequence[str], None] = 'ee2e87ddb343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: Add llm_costs table."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('llm_costs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], name='llm_costs_user_id_fkey'),
    sa.CheckConstraint("tokens_used >= 0", name='check_tokens_non_negative'),
    sa.PrimaryKeyConstraint('id', name='llm_costs_pkey')
    )
    op.create_index('idx_llm_costs_user_id', 'llm_costs', ['user_id'])
    op.create_index('idx_llm_costs_timestamp', 'llm_costs', ['timestamp'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: Remove llm_costs table."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('idx_llm_costs_timestamp', table_name='llm_costs')
    op.drop_index('idx_llm_costs_user_id', table_name='llm_costs')
    op.drop_table('llm_costs')

    # ### end Alembic commands ###
